export const CALLBACK_NAMES = {
  I_AM_CONSUMER: 'I_AM_CONSUMER',
  I_AM_SELLER: 'I_AM_SELLER',

  REGISTRATION_EDIT_PHOTO: 'REGISTRATION_EDIT_PHOTO',
  REGISTRATION_EDIT_NAME: 'REGISTRATION_EDIT_NAME',
  REGISTRATION_EDIT_ALL: 'REGISTRATION_EDIT_ALL',
  REGISTRATION_DONE: 'REGISTRATION_DONE',

  NEW_ANNOUNCEMENT: 'NEW_ANNOUNCEMENT',

  GET_ANNOUNCEMENT: 'GET_ANNOUNCEMENT',
};
