export const CALLBACK_NAMES = {
  I_AM_CONSUMER: 'I_AM_CONSUMER',
  I_AM_SELLER: 'I_AM_SELLER',

  REGISTRATION_EDIT_PHOTO: 'REGISTRATION_EDIT_PHOTO',
  REGISTRATION_EDIT_NAME: 'REGISTRATION_EDIT_NAME',
  REGISTRATION_EDIT_ALL: 'REGISTRATION_EDIT_ALL',
  REGISTRATION_DONE: 'REGISTRATION_DONE',

  NEW_ANNOUNCEMENT: 'NEW_ANNOUNCEMENT',

  GET_ANNOUNCEMENT: 'GET_ANNOUNCEMENT',
  BACK: 'BACK',
  BACK_TO_ENTER: 'BACK_TO_ENTER',
  BACK_TO_ANNOUNCEMENT: 'BACK_TO_ANNOUNCEMENT',
  DELETE_ANNOUNCEMENT: 'DELETE_ANNOUNCEMENT',
  TRY_TO_DELETE_ANNOUNCEMENT: 'TRY_TO_DELETE_ANNOUNCEMENT',
  EXIT: 'EXIT',
  ADD_TO_FAVORITED: 'ADD_TO_FAVORITED',
  REMOVE_FROM_FAVORITED: 'REMOVE_FROM_FAVORITED',

  EDIT_ANNOUNCEMENT: 'EDIT_ANNOUNCEMENT',
  EDIT_ANNOUNCEMENT_TITLE: 'EDIT_ANNOUNCEMENT_TITLE',
  EDIT_ANNOUNCEMENT_DESCRIPTION: 'EDIT_ANNOUNCEMENT_DESCRIPTION',
  EDIT_ANNOUNCEMENT_PHOTO: 'EDIT_ANNOUNCEMENT_PHOTO',
  EDIT_ANNOUNCEMENT_CATEGORY: 'EDIT_ANNOUNCEMENT_CATEGORY',
  EDIT_ANNOUNCEMENT_PRICE: 'EDIT_ANNOUNCEMENT_PRICE',

  EDIT_USER: 'EDIT_USER',
  EDIT_USER_NAME: 'EDIT_USER_NAME',
  EDIT_USER_ABOUT: 'EDIT_USER_ABOUT',
  EDIT_USER_CONTACTS: 'EDIT_USER_CONTACTS',
  EDIT_USER_CITY: 'EDIT_USER_CITY',
  EDIT_USER_PHOTO: 'EDIT_USER_PHOTO',

  MY_ANNOUNCEMENTS: 'MY_ANNOUNCEMENTS',
  MY_SELLER_PROFILE: 'MY_SELLER_PROFILE',

  BACK_TO_MY_SELLER_PROFILE: 'BACK_TO_MY_SELLER_PROFILE',
  BACK_TO_SELLER_CABINET: 'BACK_TO_SELLER_CABINET',

  FIND_DESSERT_BY_CATEGORY: 'FIND_DESSERT_BY_CATEGORY',
  FIND_DESSERT_BY_TITLE: 'FIND_DESSERT_BY_TITLE',
  FIND_DESSERT: 'FIND_DESSERT',
  RECOMMENDATIONS: 'RECOMMENDATIONS',
  EDIT_LOCATION: 'EDIT_LOCATION',
  FAVORITED_ANNOUNCEMENTS: 'FAVORITED_ANNOUNCEMENTS',
  SHOW_INFO: 'SHOW_INFO',
  SHOW_CONTACTS: 'SHOW_CONTACTS',

  NEXT_ANNOUNCEMENT: 'NEXT_ANNOUNCEMENT',
};
