export const CALLBACK_NAMES = {
  I_AM_CONSUMER: 'I_AM_CONSUMER',
  I_AM_SELLER: 'I_AM_SELLER',

  REGISTRATION_EDIT_PHOTO: 'REGISTRATION_EDIT_PHOTO',
  REGISTRATION_EDIT_NAME: 'REGISTRATION_EDIT_NAME',
  REGISTRATION_EDIT_ALL: 'REGISTRATION_EDIT_ALL',
  REGISTRATION_DONE: 'REGISTRATION_DONE',

  NEW_ANNOUNCEMENT: 'NEW_ANNOUNCEMENT',

  GET_ANNOUNCEMENT: 'GET_ANNOUNCEMENT',
  BACK: 'BACK',
  BACK_TO_ENTER: 'BACK_TO_ENTER',
  BACK_TO_ANNOUNCEMENT: 'BACK_TO_ANNOUNCEMENT',
  EDIT_ANNOUNCEMENT: 'EDIT_ANNOUNCEMENT',
  DELETE_ANNOUNCEMENT: 'DELETE_ANNOUNCEMENT',
  TRY_TO_DELETE_ANNOUNCEMENT: 'TRY_TO_DELETE_ANNOUNCEMENT',
  EXIT: 'EXIT',

  EDIT_ANNOUNCEMENT_TITLE: 'EDIT_ANNOUNCEMENT_TITLE',
  EDIT_ANNOUNCEMENT_DESCRIPTION: 'EDIT_ANNOUNCEMENT_DESCRIPTION',
  EDIT_ANNOUNCEMENT_PHOTO: 'EDIT_ANNOUNCEMENT_PHOTO',
  EDIT_ANNOUNCEMENT_CATEGORY: 'EDIT_ANNOUNCEMENT_CATEGORY',
  EDIT_ANNOUNCEMENT_PRICE: 'EDIT_ANNOUNCEMENT_PRICE',
};
