export const SCENES = {
  START_SCENE: 'START_SCENE',
  I_AM_SELLER_SCENE: 'I_AM_SELLER_SCENE',
  I_AM_CONSUMER_SCENE: 'I_AM_CONSUMER_SCENE',
  NEW_ANNOUNCEMENT: 'NEW_ANNOUNCEMENT',
  MY_ANNOUNCEMENTS: 'MY_ANNOUNCEMENTS',
  SELLER_CABINET: 'SELLER_CABINET',
  MY_SELLER_PROFILE: 'MY_SELLER_PROFILE',

  FIND_ANNOUNCEMENT_SCENE: 'FIND_ANNOUNCEMENT_SCENE',
  EDIT_LOCATION_SCENE: 'EDIT_LOCATION_SCENE',
};
